bowtie-co/houndstooth-ui

src/components/organisms/RecursiveFields/FieldSingle.jsx
remove handleArrayChange from FieldSingle
=> remove unused props

src/components/molecules/Field/FileUpload/FileUploadContainer.jsx
Allow JPG, JPGEG, Jpeg, etc to work as image extensions for preview
https://www.pivotaltracker.com/story/show/164444919
=> Add /i to ext regex for case-insensitive test

src/components/organisms/Header/Header.jsx
=> align center for header logo

package-lock.json, package.json, src/components/organisms/ItemList/ItemListContainer.jsx
Page will scroll to top onClick of a collection item.
https://www.pivotaltracker.com/story/show/163746052
=> add scroll to top

.github/CONTRIBUTING.md
=> add linting standards in pull request process

src/components/ecosystems/Repo/RepoContainer.jsx
https://www.pivotaltracker.com/story/show/164643954
=> removing queryParams from sdk params

package-lock.json, package.json, src/components/atoms/TextEditor/TextEditor.jsx, src/components/atoms/Title/Title.jsx, src/components/ecosystems/Collections/CollectionsContainer.jsx, src/components/molecules/RenameFileModal/RenameFileModal.jsx, src/components/molecules/RenameFileModal/index.js, src/components/molecules/index.js, src/components/organisms/ItemForm/ItemForm.jsx, src/components/organisms/ItemForm/ItemFormContainer.jsx
Edit collection item name and save onBlur.
https://www.pivotaltracker.com/story/show/162396488
=> Rename Collection Item

src/components/ecosystems/Collections/CollectionsContainer.jsx
https://www.pivotaltracker.com/story/show/164705732
=> Rename collection item on different branches

src/components/molecules/Field/FieldContainer.jsx
=> replace _content with _textarea

src/components/molecules/RepoControls/RepoControls.jsx
https://www.pivotaltracker.com/story/show/164875208
=> commit changes btn is now using absolute path.

package-lock.json, package.json, src/components/ecosystems/Collections/CollectionsContainer.jsx, src/components/organisms/ItemForm/ItemForm.jsx
** requires SDK merge ** 
https://github.com/bowtie-co/node-houndstooth-sdk/pull/2
https://www.pivotaltracker.com/story/show/164945106
=> Replace reference of markdown to body

src/components/organisms/ItemForm/ItemForm.jsx, src/components/organisms/ItemForm/ItemFormContainer.jsx
https://www.pivotaltracker.com/story/show/165035872
=> validation for empty file name

src/components/molecules/Field/Input/Input.jsx, src/components/organisms/RecursiveFields/FieldSingle.jsx, src/components/organisms/RecursiveFields/RecursiveFieldsContainer.jsx
- add a clearable prop to Input component
- if the value is not null, then display clearable icon
- display a placeholder only if the value is equal to null.
https://www.pivotaltracker.com/story/show/165093615
=> make fields clearable

src/components/molecules/DirCard/DirCardContainer.jsx, src/components/molecules/FileTreeMap/FileTreeMap.jsx, src/components/molecules/FileTreeMap/FileTreeMapContainer.jsx, src/components/organisms/FileSingle/FileSingle.jsx, src/components/organisms/FileSingle/FileSingleContainer.jsx, src/helpers/lists.js, src/helpers/withFormatting.jsx
- add parse image helper
- if ext is an image, render img tag instead of TextEditor
https://www.pivotaltracker.com/story/show/165040774
=> Render image in file editor

src/components/ecosystems/Repo/Repo.jsx, src/components/environments/App/AppContainer.jsx, src/components/molecules/RepoControls/RepoControls.jsx, src/components/organisms/FileSingle/FileSingle.jsx, src/components/organisms/Header/Header.jsx, src/components/organisms/ItemForm/ItemForm.jsx, src/components/organisms/RecursiveFields/RecursiveFields.jsx, src/components/organisms/TinyMCE/TinyMCE.jsx, src/scss/atoms/atoms.scss, src/scss/ecosystems/ecosystems.scss, src/scss/environments/environments.scss, src/scss/index.scss, src/scss/organisms/Wysiwyg.scss
- responsive height for tinyMce.
- media queries for tinyMce body as to not cover the toolbar.
- item form switches to full column at md.
- add currentUser in App to correctly link to users github account in header.
- remove classes from Cols and Rows and place them in wrapping divs.
https://www.pivotaltracker.com/story/show/165323826
=> File editor style

src/scss/ecosystems/ecosystems.scss
Fix side margins on repo control.
=> remove side margins on repoControl component

src/components/molecules/Field/FileUpload/FileUploadContainer.jsx, src/components/organisms/ItemList/ItemListContainer.jsx, src/components/organisms/RepoSelect/RepoSelect.jsx, src/lib/notifier.js
- Edit notifier to handle actual Errors
- Fix ItemListContainer loading default/current active item
- Applies to reload on new item
- Add `?ref=` query param to missing locations
https://www.pivotaltracker.com/story/show/166677735
Locally, viewing console for additional errors
=> Misc bug fixes

src/components/ecosystems/Collections/CollectionsContainer.jsx
- Display error notifier if item already exists with the same name
- Return rejected promise along with explicit error (to be used later once notifier settings updated)
https://www.pivotaltracker.com/story/show/166656343
Tested locally
=> Display error notifier & return rejected promise with error

config/devServer.js, craco.config.js
=> Poll for dev server

src/components/molecules/Field/FieldContainer.jsx
Allow `date`, `time` and `color` keys to trigger those field types (not just suffix with underscore)
https://www.pivotaltracker.com/story/show/166836020
=> Update detection for date, time, and color fields
